project:
  type: website
  output-dir: docs

website:
  title: "Crema 1908 Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: FirstTeam.qmd
        text: "Prima squadra"
    logo: images/Crema_logo.png
    logo-alt: "Crema 1908"

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

resources:
  - robots.txt

